### PR TITLE
added rerun_except option

### PR DESCRIPTION
**Pull request by dheepan2**
Added option support to rerun-except a particular Error/Exception.
Similar to rerun_only.

https://github.com/pytest-dev/pytest-rerunfailures/issues/179#issue-1144320553

### CODE REVIEW

**Comment by sallner** [comment]
Hello @dheepan2, thank you for your contribution. 

This looks like a nice addition to the options, although I think, this can already be accomplished in most cases with the `--only-run` argument. 

To get this PR forward it still needs some tests like https://github.com/pytest-dev/pytest-rerunfailures/blob/409822b74758476c832fa7b86d960c447d28b543/test_pytest_rerunfailures.py#L522-L552 but probably also for different errors raised. Additionally a changelog entry is needed.

**Comment by dheepan2** [comment]
> Hello @dheepan2, thank you for your contribution.
> 
> This looks like a nice addition to the options, although I think, this can already be accomplished in most cases with the `--only-run` argument.
> 
> To get this PR forward it still needs some tests like
> 
> https://github.com/pytest-dev/pytest-rerunfailures/blob/409822b74758476c832fa7b86d960c447d28b543/test_pytest_rerunfailures.py#L522-L552
> 
> but probably also for different errors raised. Additionally a changelog entry is needed.

**Comment by dheepan2** [comment]
> > Hello @dheepan2, thank you for your contribution.
> > This looks like a nice addition to the options, although I think, this can already be accomplished in most cases with the `--only-run` argument.
> > To get this PR forward it still needs some tests like
> > https://github.com/pytest-dev/pytest-rerunfailures/blob/409822b74758476c832fa7b86d960c447d28b543/test_pytest_rerunfailures.py#L522-L552
> > 
> > but probably also for different errors raised. Additionally a changelog entry is needed.

Yeah, you are right, but in certain cases with infra issues or system issues(we will not be aware of the run time Error/Exception type), during those scenarios I want the pytest to rerun any Errors other than an AssertionError.

I have added the test and updated the changelog too.

**Comment by sallner** [comment]
@dheepan2 Thank you for also putting in the effort and clean up the readme.

**Review by sallner — COMMENTED** [review]
:+1:

**Pull request merged**
