### PR TITLE
Fix Issue #239

### PR DESCRIPTION
**Pull request by metheuspsc**
Fixes issue #239 and adds test coverage

### CODE REVIEW

**Comment by icemac** [comment]
@metheuspsc Thank you for your contribution. Could you please undo the code formatting changes? This Project uses black to format the code which has its own strong opinion how to format the code, see https://github.com/pytest-dev/pytest-rerunfailures/actions/runs/6590126996/job/18552878766?pr=240 for details.

**Comment by icemac** [comment]
Currently flake8 crashes, let me update the pre-commit config in a separate PR.

**Comment by icemac** [comment]
@metheuspsc Could you please rebase your branch onto the current master branch, so the flake8 crash hopefully gets fixed?

**Comment by metheuspsc** [comment]
Rebased!

**Review by icemac — APPROVED** [review]

**Comment by icemac** [comment]
Thank you for this PR. 😃

**Pull request merged**
