### PR TITLE
Bugfix/fixture teardown twice

### PR DESCRIPTION
**Pull request by sallner**
This is a rebase of https://github.com/pytest-dev/pytest-rerunfailures/pull/144

### CODE REVIEW

**Comment by bluetech** [comment]
Hi @sallner. I have actually prepared a review of this when I was submitting the other PRs, but didn't complete it. Basically the issue is pretty complicated. Current master is doing entirely the wrong thing (completely clearing the stack), and this PR is not quite right either. I will try to find some time to finish the review.

BTW, in pytest master the `SetupState` is now clearer, stricter and more documented: https://github.com/pytest-dev/pytest/blob/16e21c22a3931bbe33fe2dbc692e149cbbb35b53/src/_pytest/runner.py#L406 might help a bit in the meantime.

**Comment by sallner** [comment]
Hi  @bluetech, I have seen your PRs and contributions to pytest core but did not see a possibility to add a new item after/during the teardown of a fixture to prevent that in case it is still needed, as we do not have the item in `teardown_exact` anymore. Do you think this or a similar approach is still possible in pytest >= 7.0?

**Comment by icemac** [comment]
Is there a new status on this PR? What are the next necessary steps?

**Comment by BeyondEvil** [comment]
Is the issue I'm seeing related to this PR?

Screenshot 2023-07-22 at 03 12 02

Basically for `flaky=N` teardown is logged (possibly also executed) N times extra.

**Comment by icemac** [comment]
As the status of this PR is unclear I am closing it now.

**Pull request closed without merging**
