### PR TITLE
Fix document starts, indentation and line length in YAML files

### PR DESCRIPTION
**Pull request by pabs3**
Suggested-by: yamllint
./.pre-commit-config.yaml
  1:1       warning  missing document start "---"  (document-start)
  10:10     error    wrong indentation: expected 10 but found 9  (indentation)
  20:10     error    wrong indentation: expected 10 but found 9  (indentation)
  26:10     error    wrong indentation: expected 10 but found 9  (indentation)
  31:10     error    wrong indentation: expected 10 but found 9  (indentation)
  35:10     error    wrong indentation: expected 10 but found 9  (indentation)

./.travis.yml
  1:1       warning  missing document start "---"  (document-start)
  20:81     error    line too long (148 > 80 characters)  (line-length)

### CODE REVIEW

**Comment by sallner** [comment]
@pabs3 Thank you for submitting this PR. Do you need this change for the packaging for debian? Or is it enough, if it ends up in the next release?

**Review by sallner — APPROVED** [review]
It is interesting, that all the documentation and examples of travis do not include the `---` in the beginning. Thank you for this PR.

**Comment by The-Compiler** [comment]
The initial `---` in YAML [are optional](https://stackoverflow.com/a/50788318/2085149) - in fact, yamllint even [has an option](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.document_start) to forbid rather than enforce them.

**Comment by pabs3** [comment]
I don't need it for Debian, this change and the others are solely
cosmetic, I just added them to polish the repo a bit based on the
output of check-all-the-things.

https://github.com/collab-qa/check-all-the-things/

The pylint tool is another thing that produces (a lot of) output for
pytest-rerunfailures, but I didn't yet have time to make it only output
higher severity things and then work on evaluating and fixing them. I
also have a limited time budget for the whole dependency chain, so I
probably won't get to this and you might want to add it to CI anyway.

Probably yamllint needs to fix the document-start warning, since the
document start is only needed when directives are present or if there
are multiple YAML documents. There is a discussion about this here:

https://github.com/adrienverge/yamllint/issues/302

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Pull request merged**
