### PR TITLE
adopt to the pytest 5.4 internal changes

### LINKED ISSUE #103: TypeError in _remove_cached_results_from_failed_fixtures with pytest 5.4
When running the testsuite with pytest master (which is soon going to become pytest 5.4), the tests fail with:

```
test_rerun_on_module_fixture_with_reruns.py RER
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/florian/proj/pytest/src/_pytest/main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/florian/proj/pytest/src/_pytest/main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/manager.py", line 337, in traced_hookexec
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/callers.py", line 52, in from_call
INTERNALERROR>     result = func()
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/manager.py", line 335, in <lambda>
INTERNALERROR>     outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/florian/proj/pytest/src/_pytest/main.py", line 272, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/manager.py", line 337, in traced_hookexec
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/callers.py", line 52, in from_call
INTERNALERROR>     result = func()
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/manager.py", line 335, in <lambda>
INTERNALERROR>     outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pytest_rerunfailures.py", line 194, in pytest_runtest_protocol
INTERNALERROR>     _remove_cached_results_from_failed_fixtures(item)
INTERNALERROR>   File "/home/florian/code/pytest-rerunfailures/.tox/py3-pytest52/lib/python3.8/site-packages/pytest_rerunfailures.py", line 135, in _remove_cached_results_from_failed_fixtures
INTERNALERROR>     result, cache_key, err = getattr(fixture_def, cached_result)
INTERNALERROR> TypeError: cannot unpack non-iterable NoneType object
```

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
fixes #103

### CODE REVIEW

**Comment by icemac** [comment]
I can't say much about the PR. At least a change log entry would be nice.

**Comment by bluetech** [comment]
Whoops, in my searches I didn't catch that `pytest-rerunfailures` uses these private fields.

Next time, I'll clone all of the repos in `pytest-dev` organization and do a grep on that, in addition to github search.

Anyway, the PR looks good to me from a pytest perspective. In the future, it would be good to provide public & documented APIs for what `pytest-rerunfailures` needs, so it doesn't break silently again.

**Comment by dirk-thomas** [comment]
I can confirm that this patch addresses the problem.

@sallner A patch release with this fix would be greatly appreciated.

**Comment by icemac** [comment]
@sallner should be back next week. Meanwhile I would be able to merge and release, but I'd like to have someone who actually reviews this PR. Is there anyone out there to do so?

**Comment by icemac** [comment]
Thank you, I just released https://pypi.org/project/pytest-rerunfailures/9.0/ including this fix.

**Pull request merged**
