### PR TITLE
Drop support for EOL Python 2.7 and 3.5

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/pytest-dev/pytest-rerunfailures/issues/121.
Fixes https://github.com/pytest-dev/pytest-rerunfailures/issues/122.

### CODE REVIEW

**Review by icemac — CHANGES_REQUESTED** [review]
I like these changes, they make the code much more readable. Thank you.

The only thing I'd like to request is an entry in the change log to make the PR perfect.

**Comment by hugovk** [comment]
Change log entry added! I also rebased to include the latest change log updates.

**Review by sallner — APPROVED** [review]
Thank you for the PR. It seems that putting "code" in f-strings helps with the black formatting very well.

**Comment by hugovk** [comment]
> Thank you for the PR. It seems that putting "code" in f-strings helps with the black formatting very well.

Yeah, stuff like this:

```python
        f"""
        import pytest
        @pytest.mark.flaky(reruns=2)
        def test_pass():
            {temporary_failure(2)}"""
```

In general, I'd avoid putting long or complex things in the `{}` brackets, to help keep things readable. For those, I'd recommend using temporary variables.

**Review by sallner — APPROVED** [review]
Thank you, that looks very good!

**Pull request merged**
