### PR TITLE
Expose `reruns` and `reruns_delay` through `pytest.ini` file

### PR DESCRIPTION
**Pull request by laky55555**

### CODE REVIEW

**Comment by icemac** [comment]
Thank you for this PR. It currently breaks many of the currently supported combinations of Python versions and pytest versions. Could you please take a look into the test failures and suggest a solution (There is #196, so I am open to drop support for old versions if needed.)

**Comment by laky55555** [comment]
Hey, thanks for the hint, I added a small change to be compatible with older versions of pytest

**Comment by icemac** [comment]
@laky55555 Could you please rebase your PR onto the current `main` branch and move the change log entry to entry for the new release.

**Comment by laky55555** [comment]
Hi @icemac, not sure if I understand the procedure.
When you say rebase PR onto the current `main` do you mean rebase and squash or just rebase as it is already ahead of `main`.
Regarding the change log, I moved the changes under `10.4` and added the release date for `10.3`

**Comment by icemac** [comment]
@laky55555 `rebase` either means `git rebase` or just to merge the current upstream `main` branch into your branch and fixing the change log so the entry belongs to the not yet released version.

**Review by icemac — APPROVED** [review]

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Pull request merged**
